name: build

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"
  pull_request:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-13
          - target: aarch64-apple-darwin
            os: macos-14
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    name: build-${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-A warnings"
          toolchain: "stable"

      - name: build winterjs
        run: |
          # cargo install --git https://github.com/wasmerio/winterjs winterjs


          git clone https://github.com/ahaoboy/winterjs winterjs
          # git clone https://github.com/wasmerio/winterjs winterjs
          cd winterjs
          cargo install --path=.

      - name: test
        run: |
          echo "console.log(1+1)" > test.js
          winterjs test.js

          which winterjs

          mkdir dist

          cp ~/.cargo/bin/winterjs ./dist
          tar -czf ./winterjs-${TARGET}.tar.gz -C dist .

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: winterjs-${{ matrix.target }}
          path: ./winterjs-${{ matrix.target }}.tar.gz
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: winterjs
          pattern: winterjs*
          merge-multiple: true

      - name: release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "winterjs/*.tar.gz"
          allowUpdates: true

  post-test:
    needs: ["release"]
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-14, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: easy-install/easy-setup@v1
        with:
          url: https://github.com/ahaoboy/winterjs-build
      - name: test
        run: |
          which winterjs
          echo "console.log(1+1)" >> ./test.js
          winterjs ./test.js
